[package]
name = "fixme"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "fixme"


[dependencies]
regex = "1.5"
lazy_static = "1.4.0"
jwalk = "0.6"
rayon = "1.5"
colored = "2.0.0"
ignore = "0.4"
git2 = "0.13"